version: "3.8"

services:
  backend:
    build: ./weather-service
    container_name: weather-backend
    ports:
      - "9090:8080"   # host:container
    networks:
      - weather-app


  frontend:
    build: ./weather-ui
    container_name: weather-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - weather-app

networks:
  weather-app:
    driver: bridge
