version: "3.9"
services:
  backend:
    build: ./weather-service
    container_name: weather-backend
    ports:
      - "8081:8080"   # host:container
    networks:
      - weather-app


  frontend:
    build:
      context: ./weather-ui
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "4200:80"
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      - backend
